### PR TITLE
pin libxml2 <2.9.11

### LINKED ISSUE #57: Please pin libxml2<=2.9.10 until lxml bug 1928795 is resolved.
Issue:

Until [`lxml` bug 1928795](https://bugs.launchpad.net/lxml/+bug/1928795) is resolved, `libxlm2` should be pinned to `<=2.9.10` otherwise things can break in very mysterious ways.  For example:

```bash
$ conda create -c conda-forge -n lxml_bug lxml
$ conda activate lxml_bug
$ python lxml_bug.py
Conversion from b'<p>bug</p' != b'<p>bug</p></body></html>\n' adds garbage.
```

```python
# lxml_bug.py
import lxml.html

s = b"<p>bug</p"
r = lxml.html.tostring(lxml.html.fromstring(s))
if not r == s:
    print(f"Conversion from {s} != {r} adds garbage.")
    assert False
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/mforbes/.conda/envs/lxml_bug:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.5.30            h033912b_0    conda-forge
certifi                   2021.5.30        py39h6e9494a_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
lxml                      4.6.3            py39hf41e7f8_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
python                    3.9.5           hd187cdc_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : lxml_bug
    active env location : /Users/mforbes/.conda/envs/lxml_bug
            shell level : 3
       user config file : /Users/mforbes/.condarc
 populated config files : /Users/mforbes/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.9.5.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /data/apps/conda  (read only)
      conda av data dir : /data/apps/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/apps/conda/pkgs
                          /Users/mforbes/.conda/pkgs
       envs directories : /Users/mforbes/.conda/envs
                          /data/apps/conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by holymonson**
fix #57

---

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by holymonson** [comment]
@ocefpaf Tests are good, would you please review this?

**Comment by ocefpaf** [comment]
LGTM but I'm a bit worried that `libxml2` is pinned for the ecosystem and this constraint here won't help much unless we "patch" the previous `lxml` built. Say, if you try to install it the solver will try to optimize and get the previous build with the latest `libxml2`.

Can you identify if the problem happens with just a few `lxml` we built? If so we can mark them broken and mitigate that.

**Comment by ocefpaf** [comment]
Merging anyway b/c regardless of patching the previous packages or marking them as broken we need this.

**Comment by holymonson** [comment]
> LGTM but I'm a bit worried that `libxml2` is pinned for the ecosystem and this constraint here won't help much unless we "patch" the previous `lxml` built. Say, if you try to install it the solver will try to optimize and get the previous build with the latest `libxml2`.
> 
> Can you identify if the problem happens with just a few `lxml` we built? If so we can mark them broken and mitigate that.

Many packages added constraint `libxml2 <2.9.11`, so they will actually get `lxml 4.6.3` instead of the latest `lxml 4.8.0`, but that's fine because the older one still works. However, there is no `lxml 4.6.3` or any suitable built on python 3.10, and this PR will fix it.

**Pull request merged**
