### PR TITLE
Drop ZPL-2.0 and GPL-2.0-only licenses

### PR DESCRIPTION
**Pull request by fhoehle**
The licenses `ZPL-2.0` and `GPL-2.0-only` apply to the `test.py` file used for unit testing `lxml`'s code; [see the file its self](https://github.com/lxml/lxml/blob/master/test.py) and [license statements at line 11](https://github.com/lxml/lxml/blob/d9edac0bde3a982e4303f7f0d73ab4dd907fc43b/LICENSES.txt#L11). 
In current conda packaging this `test.py` file is not included. [Here](https://github.com/conda-forge/lxml-feedstock/pull/81/commits/135007097c40dec82782e3f8cd37d60f045f20c3#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR44) a proposal of a test ensuring that `test.py` is not included. I'm happy if there is an alternative to achieve the same assertion.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by fhoehle** [comment]
@conda-forge/lxml this is ready for review, thanks.

**Comment by fhoehle** [comment]
> The only question I have is that I could not find the references for the ZPL-2.0. 

Sorry this is quite hidden at [line 62 in test.py](https://github.com/lxml/lxml/blob/d9edac0bde3a982e4303f7f0d73ab4dd907fc43b/test.py#L62) and I did not find any further occurances.

**Comment by ocefpaf** [comment]
Thanks @fhoehle for the PR and the explanations!

**Pull request merged**
