### PR TITLE
update to version 4.1.0

### PR DESCRIPTION
**Pull request by jjhelmus**
add jjhelmus to recipe-maintainers list

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
I wonder why Travis CI isn't showing up.  This happen with conda-forge/jupyter_console#8 as well.  

I'll try pushing an update to `psutils` from my personal fork rather than berryconda to see if that is the issue.

**Comment by jjhelmus** [comment]
Odd Travis CI was trigger find in conda-forge/psutil-feedstock#22 (berryconda) as well as conda-forge/psutil-feedstock#21 (from jjhelmus).

**Comment by ocefpaf** [comment]
psutil worked, it does look like an issue  with 'berryconda'.

But no need to resend this one. We can merge and whatch OS X builds on master.

**Comment by jjhelmus** [comment]
> But no need to resend this one. We can merge and whatch OS X builds on master.

Works for me.  I'll keep an eye on the issue and contact Travis CI if it continues.

**Comment by ocefpaf** [comment]
Which one did you send first? Maybe they have the same commit hash and one enabled the other?

**Comment by jjhelmus** [comment]
I sent the `jjhelmus` one first, that may be the cause.

**Pull request merged**
